name: ${APP_NAME}-prod

services:
  frontend:
    image: ${APP_NAME}/frontend:latest
    container_name: frontend-prod
    restart: unless-stopped
    tty: true
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports: 
      - 7000:7000  
    env_file: 
      - ./frontend/.env
    environment:
      - RUN_ON_DOCKER=on
      - BACKEND_HOST=backend
      - VITE_MODE=production

    networks:
      - app-network

  backend:
    image: ${APP_NAME}/backend:latest
    container_name: backend-prod
    restart: unless-stopped
    tty: true
    depends_on:
      - postgres
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/springbootDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: qwerty123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_MAIL_HOST: mailhog
      SPRING_MAIL_PORT: 1025 
    networks:
      - app-network
  
  postgres:
    image: postgres
    container_name: postgres-prod

    restart: unless-stopped
 
    environment:
      - POSTGRES_DB=springbootDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty123 
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data

    networks:
      - app-network

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog-prod
    restart: unless-stopped
    ports:
      - 8025:8025
      - 1025:1025
    networks:
      - app-network

volumes:
  postgres-db: 

networks:
  app-network:
    driver: bridge
